org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.java.home=/Volumes/DevDrive/Android Studio.app/Contents/jbr/Contents/Home
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
android.useAndroidX=true

# Rust / Android toolchain (used by cargo plugin tasks)
CARGO_HOME=/Volumes/DevDrive/Repositories/.cargo
RUSTUP_HOME=/Volumes/DevDrive/Repositories/.rustup
ANDROID_NDK_HOME=/Volumes/DevDrive/Android/sdk/ndk/26.2.11394342
ANDROID_HOME=/Volumes/DevDrive/Android/sdk
